name: Starting server

on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - run: npm ci
      - run: npm run start &
